model:
  device: "mps"

agent:
  epsilon_start: 1
  epsilon_final: 0.01
  epsilon_decay_last_frame: 150000
  learning_rate: 1e-4
  gamma: 0.99
  mean_rew_bound: 19
  batch_size: 32
  sync_target_frames: 1000

env:
  name: "PongNoFrameskip-v4"

replay_buffer:
  size: 10000
  replay_start_size: 10000